package keccak.math.arithmetic.zeroone

import keccak.math.arithmetic.BooleanVariable

val x0 = BooleanVariable("x0", BooleanVariable.Type.ZERO_ONE)
val x1 = BooleanVariable("x1", BooleanVariable.Type.ZERO_ONE)
val x2 = BooleanVariable("x2", BooleanVariable.Type.ZERO_ONE)
val x3 = BooleanVariable("x3", BooleanVariable.Type.ZERO_ONE)
val x4 = BooleanVariable("x4", BooleanVariable.Type.ZERO_ONE)
val x5 = BooleanVariable("x5", BooleanVariable.Type.ZERO_ONE)
val x6 = BooleanVariable("x6", BooleanVariable.Type.ZERO_ONE)
val x7 = BooleanVariable("x7", BooleanVariable.Type.ZERO_ONE)
val x8 = BooleanVariable("x8", BooleanVariable.Type.ZERO_ONE)
val x9 = BooleanVariable("x9", BooleanVariable.Type.ZERO_ONE)
val x10 = BooleanVariable("x10", BooleanVariable.Type.ZERO_ONE)
val x11 = BooleanVariable("x11", BooleanVariable.Type.ZERO_ONE)
val x12 = BooleanVariable("x12", BooleanVariable.Type.ZERO_ONE)
val x13 = BooleanVariable("x13", BooleanVariable.Type.ZERO_ONE)
val x14 = BooleanVariable("x14", BooleanVariable.Type.ZERO_ONE)
val x15 = BooleanVariable("x15", BooleanVariable.Type.ZERO_ONE)
val x16 = BooleanVariable("x16", BooleanVariable.Type.ZERO_ONE)
val x17 = BooleanVariable("x17", BooleanVariable.Type.ZERO_ONE)
val x18 = BooleanVariable("x18", BooleanVariable.Type.ZERO_ONE)
val x19 = BooleanVariable("x19", BooleanVariable.Type.ZERO_ONE)

val y0 = BooleanVariable("y0", BooleanVariable.Type.ZERO_ONE)
val y1 = BooleanVariable("y1", BooleanVariable.Type.ZERO_ONE)
val y2 = BooleanVariable("y2", BooleanVariable.Type.ZERO_ONE)
val y3 = BooleanVariable("y3", BooleanVariable.Type.ZERO_ONE)
val y4 = BooleanVariable("y4", BooleanVariable.Type.ZERO_ONE)
val y5 = BooleanVariable("y5", BooleanVariable.Type.ZERO_ONE)
val y6 = BooleanVariable("y6", BooleanVariable.Type.ZERO_ONE)
val y7 = BooleanVariable("y7", BooleanVariable.Type.ZERO_ONE)
val y8 = BooleanVariable("y8", BooleanVariable.Type.ZERO_ONE)
val y9 = BooleanVariable("y9", BooleanVariable.Type.ZERO_ONE)
